version: '2'

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    build: ./config/prometheus
    restart: always
    volumes:
      - prometheus_data:/prometheus
    depends_on:
      - alertmanager

  grafana:
    build: ./config/grafana
    restart: always
    environment:
      VIRTUAL_HOST: $MONITORING_HOSTNAME
      LETSENCRYPT_HOST: $MONITORING_HOSTNAME
    volumes:
      - grafana_data:/var/lib/grafana
    env_file: ./.env
    depends_on:
      - prometheus

  alertmanager:
    build: ./config/alertmanager
    restart: always

  monitor:
    image: thundercore/bridge-monitor
    build: ../../monitor
    restart: always
    environment:
      VIRTUAL_HOST: $METRICS_HOSTNAME
      LETSENCRYPT_HOST: $METRICS_HOSTNAME

networks:
  default:
    external:
      name: frontend_default