{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "token", "label": "Token", "query": "bridge_balance" },
   { "name": "validator", "label": "Validator", "query": "bridge_balance" },
   { "name": "network", "label": "Network", "query": "bridge_balance" }
  ]
 },
 "panels": [
  {
   "title": "Left TX in $network network",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "repeat": "network",
   "targets": [
    {
     "expr": "avg(bridge_leftTx{network=\"$network\"}) without (token)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Balance diff",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bridge_balanceDiff", "legendFormat": "{{token}}" }
   ]
  },
  {
   "title": "Left TX in $network network",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(bridge_leftTx{network=\"$network\"}) without (token)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Deposits",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bridge_deposits", "legendFormat": "{{token}}, {{network}}" },
    {}
   ]
  },
  {
   "title": "Validator balance in $network network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "repeat": "network",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bridge_balance{network=\"$network\"}) without (token)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Withdrawals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bridge_withdrawals", "legendFormat": "{{token}}, {{network}}" }
   ]
  },
  {
   "title": "Validator balance in $network network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bridge_balance{network=\"$network\"}) without (token)",
     "legendFormat": "{{validator}}"
    }
   ]
  },
  {
   "title": "Required signatures for $token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 },
   "repeat": "token",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bridge_requiredSignatures{token=\"$token\", network=\"home\"}"
    }
   ]
  },
  {
   "title": "Required signatures for $token",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "bridge_requiredSignatures{token=\"$token\", network=\"home\"}"
    }
   ]
  }
 ]
}